version: '3.8'

services:
   node_backend:
     container_name: node_docker
     image: node_docker:0.0.2
     build:
        context: .
     ports:
        - "3002:3002"
     environment:
       - PORT=3002
       - PGDATABASE=nodeDocker_db
       - PGUSER=kendrick
       - PGPASSWORD=12345
       - PGHOST=node_db
     depends_on:
       - node_db
   node_db:
     container_name: node_db
     image: "postgres:12"
     ports:
       - "5432:5432"
     environment:
       - POSTGRES_USER=kendrick
       - POSTGRES_PASSWORD=12345
       - POSTGRES_DB=nodeDocker_db

     volumes:
       - nps_data:/var/lib/postgresql/data
volumes:
  nps_data: {}