version: '3.8'

services:
   node_backend:
     container_name: node_docker
     image: node_docker:0.0.2
     build:
        context: .
     ports:
        - "3000:3000"
     environment:
       - PORT = 3000